name: Deploy para InfinityFree
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sincronizar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER  }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./htdocs/
          # Mantém os arquivos que já funcionam no servidor e não estão no GitHub
          exclude: |
            **/config.php
            **/conexao.php
            .git*
            .github*
